bot_token: "8405948402:AAH5_XJURSjoztQcpwfgTcWqKhdbn-jYyz8"
coc_api_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjM1Mjc0ZWI1LWU0M2MtNGExOC1iZDJmLWUyZWI2OTI3ODdkNiIsImlhdCI6MTc2ODMyMzU2Nywic3ViIjoiZGV2ZWxvcGVyLzQ1NmMxMWY3LTIwYmItM2I2Ni1lZTRlLTZmMmU3MjlhZDAyZCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjkwLjE1Ni4yNTQuOTciXSwidHlwZSI6ImNsaWVudCJ9XX0.QPl3Yc3n-ofMDiGfoBFBSrQn6UqmvqtT2qljAkrXHzn6FtHh3IoLnE9qGD3Q-G80hcEW_kPPjoda3LjxdiuPUQ"
clan_tag: "#2YCYJ9CQQ"
main_chat_id: -1003303283869
admin_telegram_ids:
  - 969621591
timezone: "Europe/Moscow"
database_url: "postgresql+asyncpg://cocbot:cocbot@db:5432/cocbot"
log_level: "INFO"
default_notify_channel: "dm"
